//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Inputs/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Marker"",
            ""id"": ""f65fcece-ae8f-426b-9376-28cbf07d31a8"",
            ""actions"": [
                {
                    ""name"": ""MoveKeyboard"",
                    ""type"": ""Button"",
                    ""id"": ""d8b6f70c-81ef-4e8a-962e-4e8f497157db"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveCursor"",
                    ""type"": ""Value"",
                    ""id"": ""042be877-22dd-4dc9-af32-0995aec362a7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""d1124502-bb52-4a65-9988-e74bf7cf4398"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a5c98beb-2c11-45fb-889e-302ae0d3b66b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeyboard"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""938c5ad3-e93b-43b5-9d92-ed897f2054a5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1b3082eb-b98c-4b54-8326-f3f9e709ebbc"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8a517f96-c361-44f0-b30b-9df2d63d4ef5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2ec29048-c1a6-4e36-af1e-39c1884bdc19"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2276e4b5-c8e3-4b51-95ba-3a2ab480c866"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeyboard"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cfd0e08b-8c9b-4f45-8fb8-c799d70fd1e2"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9713aa51-0c02-4812-b0c3-812d572b6d17"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""81d6e268-0d5b-43a2-b702-ff351aa70937"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ac8f7f0e-2e0b-4ffd-a2bc-2fd3e091f3cb"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4bcd8cc1-581b-4592-9fea-0260d32f9322"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a80ffc0e-860e-4bf1-922a-5511486df708"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa75658c-668a-46f7-95ee-64306c2b3046"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Item"",
            ""id"": ""9ed9a902-9633-4e92-acc9-57fb846e48f6"",
            ""actions"": [
                {
                    ""name"": ""Select First"",
                    ""type"": ""Button"",
                    ""id"": ""94a1ea9f-1a53-4f6d-917c-911363c2f14b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Second"",
                    ""type"": ""Button"",
                    ""id"": ""d2165a0c-e34c-458f-9bed-86d0837fe2c5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Third"",
                    ""type"": ""Button"",
                    ""id"": ""54bed710-a579-499b-9fea-f2ebb6478931"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Fourth"",
                    ""type"": ""Button"",
                    ""id"": ""ecbcca44-c82b-4fdb-80b5-21276811aa54"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Fifth"",
                    ""type"": ""Button"",
                    ""id"": ""b5845e2c-198c-4781-978c-4aed1e1c8b59"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Sixth"",
                    ""type"": ""Button"",
                    ""id"": ""837167ac-d033-448f-9bbc-cfe2a0d6d480"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Fertilizer"",
                    ""type"": ""Button"",
                    ""id"": ""1ee86e93-0ccb-4989-be0a-2b7908c08419"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""70731fc9-eaa2-4801-9bae-1d03559d31e1"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select First"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47ac3aab-9434-455b-bfea-43936df62a1b"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Second"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3a7fe04-d9ee-488f-892d-a59b9310f67d"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Third"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4eeb43cc-857e-4f34-8cea-f313587d900a"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Fourth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58880767-d232-49ad-b6d3-3feb50cba8fc"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Fifth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fada37c-b00c-434e-8492-e612bc8e7623"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Sixth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd556401-65df-4fdf-86c7-d3d1f5a90d7e"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Fertilizer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Marker
        m_Marker = asset.FindActionMap("Marker", throwIfNotFound: true);
        m_Marker_MoveKeyboard = m_Marker.FindAction("MoveKeyboard", throwIfNotFound: true);
        m_Marker_MoveCursor = m_Marker.FindAction("MoveCursor", throwIfNotFound: true);
        m_Marker_Select = m_Marker.FindAction("Select", throwIfNotFound: true);
        // Item
        m_Item = asset.FindActionMap("Item", throwIfNotFound: true);
        m_Item_SelectFirst = m_Item.FindAction("Select First", throwIfNotFound: true);
        m_Item_SelectSecond = m_Item.FindAction("Select Second", throwIfNotFound: true);
        m_Item_SelectThird = m_Item.FindAction("Select Third", throwIfNotFound: true);
        m_Item_SelectFourth = m_Item.FindAction("Select Fourth", throwIfNotFound: true);
        m_Item_SelectFifth = m_Item.FindAction("Select Fifth", throwIfNotFound: true);
        m_Item_SelectSixth = m_Item.FindAction("Select Sixth", throwIfNotFound: true);
        m_Item_SelectFertilizer = m_Item.FindAction("Select Fertilizer", throwIfNotFound: true);
    }

    ~@PlayerInput()
    {
        UnityEngine.Debug.Assert(!m_Marker.enabled, "This will cause a leak and performance issues, PlayerInput.Marker.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Item.enabled, "This will cause a leak and performance issues, PlayerInput.Item.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Marker
    private readonly InputActionMap m_Marker;
    private List<IMarkerActions> m_MarkerActionsCallbackInterfaces = new List<IMarkerActions>();
    private readonly InputAction m_Marker_MoveKeyboard;
    private readonly InputAction m_Marker_MoveCursor;
    private readonly InputAction m_Marker_Select;
    public struct MarkerActions
    {
        private @PlayerInput m_Wrapper;
        public MarkerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveKeyboard => m_Wrapper.m_Marker_MoveKeyboard;
        public InputAction @MoveCursor => m_Wrapper.m_Marker_MoveCursor;
        public InputAction @Select => m_Wrapper.m_Marker_Select;
        public InputActionMap Get() { return m_Wrapper.m_Marker; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MarkerActions set) { return set.Get(); }
        public void AddCallbacks(IMarkerActions instance)
        {
            if (instance == null || m_Wrapper.m_MarkerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MarkerActionsCallbackInterfaces.Add(instance);
            @MoveKeyboard.started += instance.OnMoveKeyboard;
            @MoveKeyboard.performed += instance.OnMoveKeyboard;
            @MoveKeyboard.canceled += instance.OnMoveKeyboard;
            @MoveCursor.started += instance.OnMoveCursor;
            @MoveCursor.performed += instance.OnMoveCursor;
            @MoveCursor.canceled += instance.OnMoveCursor;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
        }

        private void UnregisterCallbacks(IMarkerActions instance)
        {
            @MoveKeyboard.started -= instance.OnMoveKeyboard;
            @MoveKeyboard.performed -= instance.OnMoveKeyboard;
            @MoveKeyboard.canceled -= instance.OnMoveKeyboard;
            @MoveCursor.started -= instance.OnMoveCursor;
            @MoveCursor.performed -= instance.OnMoveCursor;
            @MoveCursor.canceled -= instance.OnMoveCursor;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
        }

        public void RemoveCallbacks(IMarkerActions instance)
        {
            if (m_Wrapper.m_MarkerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMarkerActions instance)
        {
            foreach (var item in m_Wrapper.m_MarkerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MarkerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MarkerActions @Marker => new MarkerActions(this);

    // Item
    private readonly InputActionMap m_Item;
    private List<IItemActions> m_ItemActionsCallbackInterfaces = new List<IItemActions>();
    private readonly InputAction m_Item_SelectFirst;
    private readonly InputAction m_Item_SelectSecond;
    private readonly InputAction m_Item_SelectThird;
    private readonly InputAction m_Item_SelectFourth;
    private readonly InputAction m_Item_SelectFifth;
    private readonly InputAction m_Item_SelectSixth;
    private readonly InputAction m_Item_SelectFertilizer;
    public struct ItemActions
    {
        private @PlayerInput m_Wrapper;
        public ItemActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectFirst => m_Wrapper.m_Item_SelectFirst;
        public InputAction @SelectSecond => m_Wrapper.m_Item_SelectSecond;
        public InputAction @SelectThird => m_Wrapper.m_Item_SelectThird;
        public InputAction @SelectFourth => m_Wrapper.m_Item_SelectFourth;
        public InputAction @SelectFifth => m_Wrapper.m_Item_SelectFifth;
        public InputAction @SelectSixth => m_Wrapper.m_Item_SelectSixth;
        public InputAction @SelectFertilizer => m_Wrapper.m_Item_SelectFertilizer;
        public InputActionMap Get() { return m_Wrapper.m_Item; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ItemActions set) { return set.Get(); }
        public void AddCallbacks(IItemActions instance)
        {
            if (instance == null || m_Wrapper.m_ItemActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ItemActionsCallbackInterfaces.Add(instance);
            @SelectFirst.started += instance.OnSelectFirst;
            @SelectFirst.performed += instance.OnSelectFirst;
            @SelectFirst.canceled += instance.OnSelectFirst;
            @SelectSecond.started += instance.OnSelectSecond;
            @SelectSecond.performed += instance.OnSelectSecond;
            @SelectSecond.canceled += instance.OnSelectSecond;
            @SelectThird.started += instance.OnSelectThird;
            @SelectThird.performed += instance.OnSelectThird;
            @SelectThird.canceled += instance.OnSelectThird;
            @SelectFourth.started += instance.OnSelectFourth;
            @SelectFourth.performed += instance.OnSelectFourth;
            @SelectFourth.canceled += instance.OnSelectFourth;
            @SelectFifth.started += instance.OnSelectFifth;
            @SelectFifth.performed += instance.OnSelectFifth;
            @SelectFifth.canceled += instance.OnSelectFifth;
            @SelectSixth.started += instance.OnSelectSixth;
            @SelectSixth.performed += instance.OnSelectSixth;
            @SelectSixth.canceled += instance.OnSelectSixth;
            @SelectFertilizer.started += instance.OnSelectFertilizer;
            @SelectFertilizer.performed += instance.OnSelectFertilizer;
            @SelectFertilizer.canceled += instance.OnSelectFertilizer;
        }

        private void UnregisterCallbacks(IItemActions instance)
        {
            @SelectFirst.started -= instance.OnSelectFirst;
            @SelectFirst.performed -= instance.OnSelectFirst;
            @SelectFirst.canceled -= instance.OnSelectFirst;
            @SelectSecond.started -= instance.OnSelectSecond;
            @SelectSecond.performed -= instance.OnSelectSecond;
            @SelectSecond.canceled -= instance.OnSelectSecond;
            @SelectThird.started -= instance.OnSelectThird;
            @SelectThird.performed -= instance.OnSelectThird;
            @SelectThird.canceled -= instance.OnSelectThird;
            @SelectFourth.started -= instance.OnSelectFourth;
            @SelectFourth.performed -= instance.OnSelectFourth;
            @SelectFourth.canceled -= instance.OnSelectFourth;
            @SelectFifth.started -= instance.OnSelectFifth;
            @SelectFifth.performed -= instance.OnSelectFifth;
            @SelectFifth.canceled -= instance.OnSelectFifth;
            @SelectSixth.started -= instance.OnSelectSixth;
            @SelectSixth.performed -= instance.OnSelectSixth;
            @SelectSixth.canceled -= instance.OnSelectSixth;
            @SelectFertilizer.started -= instance.OnSelectFertilizer;
            @SelectFertilizer.performed -= instance.OnSelectFertilizer;
            @SelectFertilizer.canceled -= instance.OnSelectFertilizer;
        }

        public void RemoveCallbacks(IItemActions instance)
        {
            if (m_Wrapper.m_ItemActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IItemActions instance)
        {
            foreach (var item in m_Wrapper.m_ItemActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ItemActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ItemActions @Item => new ItemActions(this);
    public interface IMarkerActions
    {
        void OnMoveKeyboard(InputAction.CallbackContext context);
        void OnMoveCursor(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
    }
    public interface IItemActions
    {
        void OnSelectFirst(InputAction.CallbackContext context);
        void OnSelectSecond(InputAction.CallbackContext context);
        void OnSelectThird(InputAction.CallbackContext context);
        void OnSelectFourth(InputAction.CallbackContext context);
        void OnSelectFifth(InputAction.CallbackContext context);
        void OnSelectSixth(InputAction.CallbackContext context);
        void OnSelectFertilizer(InputAction.CallbackContext context);
    }
}
