//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Inputs/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Marker"",
            ""id"": ""f65fcece-ae8f-426b-9376-28cbf07d31a8"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""d8b6f70c-81ef-4e8a-962e-4e8f497157db"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""d1124502-bb52-4a65-9988-e74bf7cf4398"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a5c98beb-2c11-45fb-889e-302ae0d3b66b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""938c5ad3-e93b-43b5-9d92-ed897f2054a5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1b3082eb-b98c-4b54-8326-f3f9e709ebbc"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8a517f96-c361-44f0-b30b-9df2d63d4ef5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2ec29048-c1a6-4e36-af1e-39c1884bdc19"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4bcd8cc1-581b-4592-9fea-0260d32f9322"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Item"",
            ""id"": ""9ed9a902-9633-4e92-acc9-57fb846e48f6"",
            ""actions"": [
                {
                    ""name"": ""Select First"",
                    ""type"": ""Button"",
                    ""id"": ""94a1ea9f-1a53-4f6d-917c-911363c2f14b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Second"",
                    ""type"": ""Button"",
                    ""id"": ""d2165a0c-e34c-458f-9bed-86d0837fe2c5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Third"",
                    ""type"": ""Button"",
                    ""id"": ""54bed710-a579-499b-9fea-f2ebb6478931"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""70731fc9-eaa2-4801-9bae-1d03559d31e1"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select First"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47ac3aab-9434-455b-bfea-43936df62a1b"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Second"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3a7fe04-d9ee-488f-892d-a59b9310f67d"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Third"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Marker
        m_Marker = asset.FindActionMap("Marker", throwIfNotFound: true);
        m_Marker_Move = m_Marker.FindAction("Move", throwIfNotFound: true);
        m_Marker_Select = m_Marker.FindAction("Select", throwIfNotFound: true);
        // Item
        m_Item = asset.FindActionMap("Item", throwIfNotFound: true);
        m_Item_SelectFirst = m_Item.FindAction("Select First", throwIfNotFound: true);
        m_Item_SelectSecond = m_Item.FindAction("Select Second", throwIfNotFound: true);
        m_Item_SelectThird = m_Item.FindAction("Select Third", throwIfNotFound: true);
    }

    ~@PlayerInput()
    {
        UnityEngine.Debug.Assert(!m_Marker.enabled, "This will cause a leak and performance issues, PlayerInput.Marker.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Item.enabled, "This will cause a leak and performance issues, PlayerInput.Item.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Marker
    private readonly InputActionMap m_Marker;
    private List<IMarkerActions> m_MarkerActionsCallbackInterfaces = new List<IMarkerActions>();
    private readonly InputAction m_Marker_Move;
    private readonly InputAction m_Marker_Select;
    public struct MarkerActions
    {
        private @PlayerInput m_Wrapper;
        public MarkerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Marker_Move;
        public InputAction @Select => m_Wrapper.m_Marker_Select;
        public InputActionMap Get() { return m_Wrapper.m_Marker; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MarkerActions set) { return set.Get(); }
        public void AddCallbacks(IMarkerActions instance)
        {
            if (instance == null || m_Wrapper.m_MarkerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MarkerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
        }

        private void UnregisterCallbacks(IMarkerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
        }

        public void RemoveCallbacks(IMarkerActions instance)
        {
            if (m_Wrapper.m_MarkerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMarkerActions instance)
        {
            foreach (var item in m_Wrapper.m_MarkerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MarkerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MarkerActions @Marker => new MarkerActions(this);

    // Item
    private readonly InputActionMap m_Item;
    private List<IItemActions> m_ItemActionsCallbackInterfaces = new List<IItemActions>();
    private readonly InputAction m_Item_SelectFirst;
    private readonly InputAction m_Item_SelectSecond;
    private readonly InputAction m_Item_SelectThird;
    public struct ItemActions
    {
        private @PlayerInput m_Wrapper;
        public ItemActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectFirst => m_Wrapper.m_Item_SelectFirst;
        public InputAction @SelectSecond => m_Wrapper.m_Item_SelectSecond;
        public InputAction @SelectThird => m_Wrapper.m_Item_SelectThird;
        public InputActionMap Get() { return m_Wrapper.m_Item; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ItemActions set) { return set.Get(); }
        public void AddCallbacks(IItemActions instance)
        {
            if (instance == null || m_Wrapper.m_ItemActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ItemActionsCallbackInterfaces.Add(instance);
            @SelectFirst.started += instance.OnSelectFirst;
            @SelectFirst.performed += instance.OnSelectFirst;
            @SelectFirst.canceled += instance.OnSelectFirst;
            @SelectSecond.started += instance.OnSelectSecond;
            @SelectSecond.performed += instance.OnSelectSecond;
            @SelectSecond.canceled += instance.OnSelectSecond;
            @SelectThird.started += instance.OnSelectThird;
            @SelectThird.performed += instance.OnSelectThird;
            @SelectThird.canceled += instance.OnSelectThird;
        }

        private void UnregisterCallbacks(IItemActions instance)
        {
            @SelectFirst.started -= instance.OnSelectFirst;
            @SelectFirst.performed -= instance.OnSelectFirst;
            @SelectFirst.canceled -= instance.OnSelectFirst;
            @SelectSecond.started -= instance.OnSelectSecond;
            @SelectSecond.performed -= instance.OnSelectSecond;
            @SelectSecond.canceled -= instance.OnSelectSecond;
            @SelectThird.started -= instance.OnSelectThird;
            @SelectThird.performed -= instance.OnSelectThird;
            @SelectThird.canceled -= instance.OnSelectThird;
        }

        public void RemoveCallbacks(IItemActions instance)
        {
            if (m_Wrapper.m_ItemActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IItemActions instance)
        {
            foreach (var item in m_Wrapper.m_ItemActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ItemActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ItemActions @Item => new ItemActions(this);
    public interface IMarkerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
    }
    public interface IItemActions
    {
        void OnSelectFirst(InputAction.CallbackContext context);
        void OnSelectSecond(InputAction.CallbackContext context);
        void OnSelectThird(InputAction.CallbackContext context);
    }
}
